services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: projectdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin   
    depends_on:
      - postgres

  backend:
    build:
      context: ./project-management-backend
      dockerfile: Dockerfile
    container_name: project-management-backend
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/projectdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      JWT_SECRET: mySuperSecretJwtKeyForProjectManagement123!
      APP_ADMIN_EMAIL: admin@pms.local
      APP_ADMIN_PASSWORD: admin123
      APP_ADMIN_NAME: System Admin
      APP_CORS_ALLOWED_ORIGINS: http://localhost:5173,http://127.0.0.1:5173
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: project-management-frontend
    restart: on-failure
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
  pgadmin_data:
